# 基本連線設定
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=paw_poster;encrypt=false
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 自動建立表格
spring.jpa.hibernate.ddl-auto=update

# 關閉 Hibernate 的連線資訊
logging.level.org.hibernate.orm.connections.pooling=WARN
